baseURL = 'https://polionus.github.io/'
languageCode = 'en-us'
title = 'Armin Ashrafi'
theme = 'hugo-PaperMod'

[markup.goldmark.renderer]
unsafe= true

[params]
  disableHomePostsSection = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

